# endings ---------------------------------------------------------------------------
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\&")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ et$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ et\\ ")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ al$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ et\\ al\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ ex$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\,$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\,")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\)")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\(")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\?")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ in\\ litt")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ in\\ ")]



# early shots -----------------------------------------------------------------------
omnida2[,clean_name := str_remove_all(clean_name, pattern = "WSmith")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hanna\\ et\\ Grant")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "HL\\.Smith")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "WM\\.Smith")]

# test = "Achnanthes baldjickii (Brightwell) Grunow in Cl.& Grun.var. lorenziana (Grun.) Ross"
# test %>% str_remove_all(pattern = "\\(.*\\)")
# A ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "A\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ag\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Abdin")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Aboal")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Akbulut")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Akiba")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Agardh")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Al-Handal")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Aleem")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Alfinito")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Alles")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Allorge")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Amoss\\é")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Amosse")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Andersen")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ando$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Andresen")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Andrews")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Angst")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Antoniades")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Archibald")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Arnott")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "ASA")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Atlas")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Atkinson")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Auerswald")]

# B ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "B\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Baardseth")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bachman")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bafana")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bailey-Watts")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bailey")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bak")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Baldauf")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Baley-Watts")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Barber")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Barker")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Baron")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Barron")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Basson")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bastow")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Becerril")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Becker")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bergey")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bergon")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Berg")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Berard-Therriault")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Berthon")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bertrand")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bethge")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Beyens")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Biggs")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bily")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bleisch")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bock")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Boden")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Booth")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bonik")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Boonyapiwat")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bory")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bourrelly")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bour\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bourr\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Boyer")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Boye-Petersen")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bramburger")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Brander")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Brockmann")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Breb\\.ex")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Breb\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Breb\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bréb\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Brebisson")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Brébisson")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bréb")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Brendemuhl")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Brigger")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bristol")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bruder")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Brutschy")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Buczko")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bruegger")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Brun")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Brzezinska")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bukhtiyarova")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bukhtiyatrova")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Bukht")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Burford")]

# C ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "C\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "CE")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Caljon")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Camburn")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Campis")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Cantonati")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Cardinal")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Carlson")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Carmichael")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Carter")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Cassie")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Castracane")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Cavacini")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Cavicini")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Charles")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Chaumont")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Chang")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Chan")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Chase")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Cheng")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Chen")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Chernov")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Cholnoky")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Choln\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Chonoky")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Churs\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ciesielski")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Clarke")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Clason")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Cl\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Cle\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Clece-")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Cleve-Euler")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Cleve-euler")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Cleve")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Clve")]
#omnida2[,clean_name := str_remove_all(clean_name, pattern = "cleve")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Cocquyt")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Cohu")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Comber")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Compere")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Compère")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Cooper")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Cordini")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Coste")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Costa")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Cottam")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Couté")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Cox")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Crawford")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Cremer")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Crosby")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Cupp")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Czarnecki")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Czarn\\.")]

# D ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "D\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "De\\ Notaris")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "De\\ Oliveira")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "De\\ Smet")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "De\\ Stefano\\ Marino")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "De\\ Stefano\\ \\&\\ Marino")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "De\\ Stefano")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "De\\ Toni")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Darley")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Deby")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Dempsey")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Denny")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Denys")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Descy")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Desikachary")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Desikachary")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Dickie")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Dillwyn")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Dippel")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "doello-juradoi")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Donkin")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Dorofeyuk")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Druart")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Doucette")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Dumont")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Duran")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Dute")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Duthie")]


# E ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "E\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ector")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Edgar")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Edlund")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Encinas")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ehr\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ehrenberg")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ehrenb\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ehrlich")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Elm$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Elmore")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "etBrun")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ emend\\ ")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ emend$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "English")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Escobar")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Eulenstein")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Euler")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Eule")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "-Eul")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Evans")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "ex\\ Grev\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ ex\\ ")]

# F ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "F\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Fabri")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Febiger")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Febiger\\ H")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Fenner")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ferguson")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Fernandes")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ferrario")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ferrari")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Flögel")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Florin")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Flower")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "fo\\.ikpukensis")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Foged")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Fontell")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "forma\\ tenuior")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Forti")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Fourtanier")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Francoeur")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Frenguelli")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Frengeuelli")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Freng\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Freese")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Fricke")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Fritsch")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Fryxell")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Fuge")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Fukushima")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Fusey")]

# G ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "G\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gaarder")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gaillon")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gaiser")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gallik")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gao")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Garcia-Baptista")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Garcia-Rodriguez")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Garcia-Rodri")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Garcia")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gayoso")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Geitler")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gerloff")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Germain")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gerasimiuk")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gerasi")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gandhi")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gardner")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Garner")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gasse")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gedde")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Geißler")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Genkal")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gerloff")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gibson")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Giffen")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gmelin")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Glaiser")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gleser")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Glezer")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gombos")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gotoh")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gran")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Greenleaf")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Greg\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gregory")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Greguss")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Greville")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Grev\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Grev")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "group 1")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "group 2")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "group 3")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Grove")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "GunowV")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Grunow")]
#omnida2[,clean_name := str_remove_all(clean_name, pattern = "grunow")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Grun\\.in")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Grun\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Grun")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Guermeur")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Guerrero")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Guillard")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Guo\\ Xie\\ Liu")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gowthaman")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Guslakov")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gusliakov")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Gutwinskii")]


# H ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "H\\.L\\.Smith")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "H\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hagelstein")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hains")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hajos")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hakansson")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Håkansson")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Halden")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hallegraeff")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hallegraef")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hamilton")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hantzsch$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ Hantzsch")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hantz\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Harper")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hartley")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Harvey")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Harwood")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hassall")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hasle$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ Hasle")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Haworth")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hayashi")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "head")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Heiberg")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "HeidenKolbe")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Heiden")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Heid")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Heimdal")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hein")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hellermann")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hellerman")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hell")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Helmcke")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hendey")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hensen")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Herbst")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Héribaud")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "heribaud")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hérib\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Herib\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hernandez")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Herzig")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hickie")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hilse")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hinz")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ hinz\\ ")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "HJeiden")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hlubikova")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hoban")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hodgson")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hofmann")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hohn")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Holmes")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Holmboe")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Honigman")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Horikawa")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Houki")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Houk")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hubbard")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hustedt")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hust\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hutedt")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Huste$")]

# I ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "Idei")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Iserentant")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ivanov")]

# J ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "J\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Jahn")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Janisch")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Jarlman")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Jasnitzky")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Jao")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Jentzsch")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "JiaYing")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Johansen")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "John")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Jones")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Jordan")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Jørgensen")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Jorgensen")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Jouse")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Jousé")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Jous\\é")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Juhlin-Dannfelt")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Jurilj")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Jurkschat")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Jüttner")]


# K ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "K\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kaczmarska")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kalbe")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kanaya")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Karaeva")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Karluki")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Karsten")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kelly")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kemp")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Khursevich")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kingston")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kirchner")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kisselev")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kitton")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Klee")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kling")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Klöser")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Knudson")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ko-bayashi")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Koc\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kogan")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kooistra")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Konno")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Koppen")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Koslova")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Korotkevich")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kozlova")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Krammert")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Krammer")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kreis")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Krei$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Krenner")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Krishnamurthy")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Krstic")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kobayasi$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ Kobayasi\\ ")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kobayasi$")] # willfull repetition
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kob\\.")] 
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kociolek")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kociol\\.Stoerm\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kociol\\.\\&Stoerm\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kolbe")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Komura")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Konig")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "König")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kopalova")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Körner")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "KrasskeHustedt")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Krasske")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Krassk")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kufferath")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Khur")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kuptseva")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kupt\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kützing")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kütz\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kütz")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kuetzing")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kulikovskiy")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kusber")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kuylenstierna")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kuzmina")]


# L ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "L\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ L$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ Li$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "LB")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Laird")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lange-Bertalot")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lange-Berrtalot")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lange\\ Bertalot")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lange-Bert")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "lange-bertalot")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lange-bertalot")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lange-B\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lange-")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lagerstedt")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lag\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lauby")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lebouvier")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Leclercq")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ledeganck")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lee")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Le$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Legler")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lemmermann")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lemm\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Leudiger-Fortmorel")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Leuduger-Fortmorel")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Leud\\.-Fortmorel")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Levander")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lewis")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Levkov")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "levkov")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ Li\\ ")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "-Li\\ Y\\.-\\ Chiang")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Licea")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ligowski")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Litt\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "List")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Livingston")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Liu\\ Chin")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lobban")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Locker")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lohman")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Long\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Long")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lowe")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ludwig")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lund")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lupikina")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lyngbye")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Lyngb\\.")]

# M ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "M\\.\\ Peragallo")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "M$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "M\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ma$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Mahood")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Mahoney")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Maidana")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Maillard")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Main")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Makarova")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Manguin")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Mang")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Mann")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Man$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Margalef")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Maruyama")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Marvan")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Massé")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Mataloni")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Matvienko")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Mayama")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Mayer")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "McCall")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "McMinn")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Mc\\ Call")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "McGregor")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "McIntire")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Meakin")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Medlin")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Meister")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Meist$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Mereschkowsky")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Metzeltin")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Metzelti")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Metzelt\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Metz")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Messikommer")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Meave")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Meyer")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Meunier")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Michailov")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Miho")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Mills")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Missuna")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Molder")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Moeller")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Moller")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Möller")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Möll")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Monnier")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Montagne")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Morales")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Moreno")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Moser")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Mnaguin")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Muftah")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Muller")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Müller")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Müll\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Muschler")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Muylaert")]

# N ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "N\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Naegeli")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Nagumo")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Nagasawa")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Nakov")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Natour")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Negoro")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Nemoto")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Nergui")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Nikolaev")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Nitzsch\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ Nitzsch$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ Nitzsch\\ ")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ non$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ non\\ ")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Norman")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ Norm\\ ")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Nöthig")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "nov\\.var")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "novar\\.comb")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Novarino")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Nùñez-Avellaneda Vouilloud")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Nùñez-Avellaneda Vouilloud")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Nygaard")]

# O ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "O$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ o$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "O\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "O\\'Meara")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Oest\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ Ostrup")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ostrup$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Oestrup$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ Oestrup")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Osada")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Østrup")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ognjanova")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ohtsuka")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Okuno")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Olney")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Oppenheim")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Orlando")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ostenfeld")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Otto")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ozornina")]

# P ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "P\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Paddock")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Pantocsek")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Pant\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Passauer")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Patrick")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Prasad")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Pavlov")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Pelletan")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Petersen")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Peragallo")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Perag\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Petit")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = ".Pet")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Pfannkuche")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Pfitzer")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Pienaar")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Pillsbury")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Pioz")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Playfair")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "=Placoneis")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ponader")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Poretskaya")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Poretzkiy")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Poretsky")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Poretzsky")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Por\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Potapova")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Poulin")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Pozorski")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Prema")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Priddle")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Pritchard")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Proschkina-Lavrenko")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Prosckina-Lavrenko")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Proschkina-Lawrenko")]


# Q ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "Quint")]

# R ---------------------------------------------------------------------------------


omnida2[,clean_name := str_remove_all(clean_name, pattern = "R\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Rabh\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Rabenhorst")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ralfs")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ramfsjell")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Rattray")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Re$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Reichardt")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Reichelt")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Reich\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Reid")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Reimer$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Reinhold")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Reinsch")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Reviers")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Rev$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Rhode")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Riaux-Gobin")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ribeiro")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ricard")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Richardson")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Richter")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Rich")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Rimet")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Rincé")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Rivera")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Roberts")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Robert")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ross")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = ".Roper")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Roth")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Rott")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Rochoux\\ d'Aubert")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Round")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Roux")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Rubenstein")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Rumrich")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ruppel")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ryabushko")]

# S ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "S\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sm\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ Sm\\ ")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ S$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sabater")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sabbe\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sabbe")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Saito")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Salah")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sala")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sakai")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sanchez-Castillo")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "sangustiminus")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sar")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sato")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sawatari")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sawai")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "sbohemicum")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Schaarschmidt")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Schadb\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Scherer")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Schmidt")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Scmidt")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Schimanski")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Schimper")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Schindler")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Schoemann")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Schoeman")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Schoenfeld")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Schrader")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Schroeder")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Schroeter")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Schröder")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Schultze")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Schulz")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Schumann")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Schuman")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Schuette")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Schwabe")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Schwarz")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sebring")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Selva")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ sensu")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Servant-Vildary")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Shaboldt")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Shadbolt")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sherwood")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sheshukova-Poretskaya")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sheshukova")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sheshukov")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Shinneman")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Shiono")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Shoeman")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Silva")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Simonsen")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Simons")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Simola")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sims")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sippe")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Siver")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Skabicevsky")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Skabitchesky")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Skabitschewsky")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Skabichevski")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Skabitschevsky")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Skvortzow")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Skvotzow")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Skvortzov")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Skv\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Slavik")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Smith")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Snoeijs")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Soninkhishig")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sovereign")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Spaulding")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sreenivasa")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Srel\\'nikova")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Staab")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Stachura-Suchoples")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Stachura")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Stadner")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Steindorf")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Steinberg")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Steinitz-Kannan")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Stenoneis")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sterrenburg")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Stickle")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Stidolph")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Stoermer")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Stoelzel")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Stosch")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Stradner")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sturt")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sullivan")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sunesen")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Sundström")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Suto")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Syvertsen")]

# T ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "T\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Taasen")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Tagliaventi")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Takahashi")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Takano")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Tanaka")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Tanimura")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Taylor")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Tempere")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Temp\\ère")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Temp\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Thomas")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Thwaites")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Thum")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Tiffany")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Turpin")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Tomas")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Torka")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Torgan")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Toyoda")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Tremarin")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Trentepohl")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Trifonova")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Truan\\ y\\ Luard")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Tsarenko")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Tudesque")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Tuji")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Tweed")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Tynni")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "type")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "TypeTDI3")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "TDI3")]


# U ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ulanova")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Underwood")]

# V ---------------------------------------------------------------------------------


omnida2[,clean_name := str_remove_all(clean_name, pattern = "V\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Van\\ Dam")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Van\\ de\\ Vijver")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Van\\ Heurck")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "van\\ Heurck")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "van\\ Goor")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Van\\ Goor")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Heurck")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Van\\ Landingham")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Vaneslander")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Vanhoutte")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Vekhov")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Venkataraman")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Villareal")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Voigt")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Volcani")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Von\\ Quillfeldt")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "von\\ Stosch")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "v\\.\\ Stosch")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Vyverman")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "von$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "var$")]

# W ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "W\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "w\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "W$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Wm\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Wm")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Wachnicka")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Wahrer")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Walker")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Wallace")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Wallich")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Watkins")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Weckström")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Werum")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "West")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Wetzel")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Williams")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Willmann")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Winsborough")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Wislouch")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Wisl\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Witak")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Witk\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Witon")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Witkowski")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Witt")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Wojtal")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Wolfe")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Wolle")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Woodhead")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Wood")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Wormley")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Wsmith")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Wunsam")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Wuthrich")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Wuttrich")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Wydrzycka")]


# X ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "Xie Li")]

# Y ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "Y\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Yanagisawa")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Yanasigawa")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Yallop")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Yang")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Yermoloff")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Yohn")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Yoshitake")]

# Z ---------------------------------------------------------------------------------

omnida2[,clean_name := str_remove_all(clean_name, pattern = "Zacharias")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Zackenberg")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Zach\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Zalat")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Zanon")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Zhu")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Ziadarova")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Zidarova")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Zimmermann")]

# MISC ------------------------------------------------------------------------------
## -- white space 
omnida2[,clean_name := str_replace_all(clean_name, pattern = "\\ \\ ", replacement = "\\ ")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "\\ \\ ", replacement = "\\ ")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "\\ \\ ", replacement = "\\ ")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "\\ \\ ", replacement = "\\ ")]
omnida2[, clean_name := str_trim(clean_name, "both")]

# taxonomic endings ---------------------------------------------------------------
omnida2[,clean_name := str_replace_all(clean_name, pattern = "aff\\.", replacement = "var\\.")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "f\\.", replacement = "var\\.")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "fo\\.", replacement = "var\\.")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "\\ fo\\ ", replacement = "var\\.")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "spp\\.", replacement = "var\\.")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "ssp\\.", replacement = "var\\.")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "v\\.", replacement = "var\\.")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "morphotype\\ ", replacement = "var\\.")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "morpho\\ ", replacement = "var\\.")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "\\ var\\ ", replacement = "var\\.")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "\\ subsp\\.\\ ", replacement = "var\\.")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "\\ subsp\\.", replacement = "var\\.")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "\\ var\\.\\ var\\.", replacement = "var\\.")]
#omnida2[,clean_name := str_remove_all(clean_name, pattern = "sp\\.")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "\\ var\\ ", replacement = "\\ var\\.")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "\\ var\\.\\ ", replacement = "\\ var\\.")]


## -- white space
omnida2[,clean_name := str_replace_all(clean_name, pattern = "\\ \\ ", replacement = "\\ ")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "\\ \\ ", replacement = "\\ ")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "\\ \\ ", replacement = "\\ ")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "\\ \\ ", replacement = "\\ ")]
omnida2[, clean_name := str_trim(clean_name, "both")]


# 2nd round  ------------------------------------------------------------------------
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Brightwell")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Heribaud")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\=Karayevia")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Kützing")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Manuskriptnamen")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Poretzky")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Straub")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\'manuskriptnamen\\'")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "KLB91p67f37/24-40")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "K91p67f37/24-40")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "K\\ütz\\.")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "1937")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "1875")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "1871")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "1836")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "1880")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "1882")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "1853")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "1862")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "1878")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "1932")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "1874")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "1894")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\=sia")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Hanna$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Tahiti\\ 3708")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Le$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "Vis$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\ \\-$")]
omnida2[,clean_name := str_remove_all(clean_name, pattern = "\\.$")]

# Manual ----------------------------------------------------------------------------
omnida2[taxon == "Achnantheiopsis delicatula (Kützing) Lange-Bertalot", 
        clean_name := "Achnantheiopsis delicatula"]
omnida2[taxon == "Achnanthes affinis Grunow in Cleve & Grunow (Achnanthidium)", 
        clean_name := "Achnanthes affinis"]
omnida2[clean_name == "Achnanthes arenaria Amossé", 
        clean_name := "Achnanthes arenaria"]
omnida2[taxon == "Amphora clevei Grunow Schmidt & al.", 
        clean_name := "Amphora clevei"]

omnida2[taxon == "Amphora lange-bertalotii Levkov & Metzeltin", 
        clean_name := "Amphora lange-bertalotii"]

omnida2[taxon == "Amphora lange-bertalotii Levkov & Metzeltin var.tenuis Levkov & Metzeltin", 
        clean_name := "Amphora lange-bertalotii var.tenuis"]

omnida2[taxon == "Navicula cuspidata Kützing var.heribaudii M.Peragallo", 
        clean_name := "Navicula cuspidata var.heribaudii"]

omnida2[taxon == "Navicula menisculus Schumann var. grunowii Lange-Bertalot", 
        clean_name := "Navicula menisculus var.grunowii"]

omnida2[taxon == "Peronia heribaudii Brun & Peragallo", 
        clean_name := "Peronia heribaudii"]

omnida2[taxon == "Achnanthes clevei Grunow var. clevei (=Karayevia)", 
        clean_name := "Achnanthes clevei var.clevei"]
omnida2[clean_name == "Amphora neglecta Stoermer et Yang f.densestriata Foged", 
        clean_name := "Amphora neglecta var.densestriata"]
omnida2[clean_name == "Achnanthes convergensabnormal form", 
        clean_name := "Achnanthes convergens abnormal form"]
omnida2[clean_name == "Achnanthidium lapidosum Kobayasi al", 
        clean_name := "Achnanthidium lapidosum"]
omnida2[clean_name == "Achnanthidium saprophilum Kobayasi", 
        clean_name := "Achnanthidium saprophilum"]
omnida2[taxon == "Actinella lange-bertalotii Kociolek", 
        clean_name := "Actinella lange-bertalotii"]
omnida2[taxon == "Hippodonta pseudacceptata(Kobayasi) Lange-Bertalot Metzeltin & Witkowski", 
        clean_name := "Hippodonta pseudacceptata"]
omnida2[taxon == "Kobayasiella lange-bertalotii Metzeltin", 
        clean_name := "Kobayasiella lange-bertalotii"]
omnida2[taxon == "Nitzschia tryblionella Hantzsch in Rabh.var.salinarum Grunow in Cl.& Grunow", 
        clean_name := "Nitzschia tryblionella var.salinarium"]
omnida2[taxon == "Nitzschia vermicularis(Kützing)Hantzsch abnormal form", 
        clean_name := "Nitzschia vermicularis"]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "coffeaeformisvar", replacement = "coffeaeformis\\ var")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "Rhaphoneis Raphoneis", replacement = "Raphoneis")]
omnida2[clean_name == "a lewisiana", clean_name := "Frickea lewisiana"]


## -- white spaces 
omnida2[,clean_name := str_replace_all(clean_name, pattern = "\\ \\ ", replacement = "\\ ")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "\\ \\ ", replacement = "\\ ")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "\\ \\ ", replacement = "\\ ")]
omnida2[,clean_name := str_replace_all(clean_name, pattern = "\\ \\ ", replacement = "\\ ")]
omnida2[, clean_name := str_trim(clean_name, "both")]