# -------------------------------------- #
### --- manual fixes               --- ### 
### --- in harmonization of diatoms --- ### 
# -------------------------------------- #

# --------------- #
# called by: 
#               04.harmonize_diatoms_diathor.R
# --------------- #


data[species == "Achnanthes exigua"  , species_update := "Achnanthidium exiguum"]
data[species == "Achnanthes flexella", species_update := "Eucocconeis flexella"]
data[species == "Achnanthes laevis"  , species_update := "Eucocconeis laevis"]
data[species == "Achnanthes linearis f.curta", species_update := "Achnanthidium minutissimum"]
data[species == "Achnanthes minutissima", species_update := "Achnanthidium minutissimum"]
data[species == "Achnanthes oestrupii", species_update := "Planothidium oestrupii"]
data[species == "Achnanthidium chlidanos", species_update := "Psammothidium chlidanos"]
data[species == "Achnanthidium delmontii", species_update := "Achnanthidium delmontii"]
data[species == "Achnanthidium exile", species_update := "Achnanthidium exile"]
data[species == "Achnanthidium hoffmannii", species_update := "Achnanthidium hoffmannii"]
data[species == "Achnanthidium linearoides", species_update := "Achnanthidium anastasiae"]
data[species == "Achnanthidium minutissimum f.inconspicuum", species_update := "Achnanthidium minutissimum"]
data[species == "Achnanthidium thermale", species_update := "Crenotia thermalis"]
data[species == "Achnantidium lineare", species_update := "Achnantidium lineare"]
data[species == "Adlafia muralis", species_update := "Adlafia minuscula var.muralis"]
data[species == "Amphora coffeaeformis", species_update := "Halamphora coffeaeformis"]
data[species == "Aulacoseira ambigua f.curvata", species_update := "Aulacoseira ambigua var.curvata"]
data[species == "Aulacoseira distans tenella", species_update := "Aulacoseira distans var.tenella"]
data[species == "Brachysira calcicola", species_update := "Brachysira calcicola"]
data[species == "Brachysira vitrea f.lanceolata", species_update := "Brachysira vitrea var.lanceolata"]
data[species == "Caloneis amphisbaena", species_update := "Caloneis amphisbaena"]
data[species == "Caloneis cleve", species_update := "Caloneis clevei"]
data[species == "Cocconeis placentula", species_update := "Cocconeis placentula"]
data[species == "Craticula riparia", species_update := "Craticula riparia"]
data[species == "Crenotia thermalis", species_update := "Crenotia thermalis"]
data[species == "Cyclotella atomus var.gracilis", species_update := "Cyclotella atomus var.gracilis"]
data[species == "Cymbella excisa", species_update := "Cymbella excisa"]
data[species == "Cymbella kolbei", species_update := "Cymbella kolbei"]
data[species == "Cymbella neolanceolata", species_update := "Cymbella neolanceolata"]
data[species == "Cymbella neoleptoceros", species_update := "Cymbella neoleptoceros"]
data[species == "Cymbella subtruncata", species_update := "Cymbella subtruncata"]
data[species == "Cymbella tridentina", species_update := "Cymbella tridentina"]
data[species == "Cymbella tropica", species_update := "Cymbella tropica"]
data[species == "Cymbella turgidula", species_update := "Cymbella turgidula"]
data[species == "Cymbella vulgata", species_update := "Cymbella vulgata"]
data[species == "Cymbopleura angustata", species_update := "Cymbopleura angustata"]
data[species == "Cymbopleura frequens", species_update := "Cymbopleura frequens"]
data[species == "Cymbopleura hustedtii", species_update := "Cymbopleura hustedtii"]
data[species == "Cymbopleura kuelbsii", species_update := "Cymbopleura kuelbsii"]
data[species == "Cymbopleura lata", species_update := "Cymbopleura lata"]
data[species == "Decussata placenta", species_update := "Decussiphycus placenta"]
data[species == "Delicata delicatula", species_update := "Delicatophycus delicatulus"]
data[species == "Delicata krammer", species_update := "Delicata krammeri"]
data[species == "Diadesmis confervacea", species_update := "Diadesmis confervacea"]
data[species == "Diatoma tenue", species_update := "Diatoma tenuis"]
data[species == "Diatoma tenuis var.moniliformis", species_update := "Diatoma moniliformis"]
data[species == "Diatoma vulgaris f.breve", species_update := "Diatoma vulgaris var.brevis"]
data[species == "Diploneis ostracodarum", species_update := "Diploneis ostracodarum"]
data[species == "Diploneis petersenii", species_update := "Diploneis peterseni"]
data[species == "Encyonema leibleinii", species_update := "Encyonema leibleinii"]
data[species == "Encyonopsis microcephala var.robusta", species_update := "Encyonopsis microcephala var.robusta"]
data[species == "Eolimna elorantana", species_update := "Sellaphora elorantana"]
data[species == "Epithemia argus", species_update := "Epithemia argus"]
data[species == "Epithemia turgida", species_update := "Epithemia turgida"]
data[species == "Eunoria curtagrunowii", species_update := "Eunotia curtagrunowii"]
data[species == "Eunotia ambivalens", species_update := "Eunotia ambivalens"]
data[species == "Eunotia arcus", species_update := "Eunotia arcus"]
data[species == "Eunotia biceps", species_update := "Eunotia biceps"]
data[species == "Eunotia eurycephaloides", species_update := "Eunotia eurycephaloides"]
data[species == "Eunotia incisa", species_update := "Eunotia incisa"]
data[species == "Eunotia monodon", species_update := "Eunotia monodon"]
data[species == "Eunotia muscicola", species_update := "Eunotia muscicola"]
data[species == "Eunotia muscicola var.perminuta", species_update := "Eunotia muscicola var.perminuta"]
data[species == "Eunotia naegelii", species_update := "Eunotia naegelii"]
data[species == "Eunotia paludosa", species_update := "Eunotia paludosa"]
data[species == "Eunotia parallela", species_update := "Eunotia parallela"]
data[species == "Eunotia pectinalis", species_update := "Eunotia pectinalis"]
data[species == "Eunotia rhynchocephala", species_update := "Eunotia rhynchocephala"]
data[species == "Eunotia serra", species_update := "Eunotia serra"]
data[species == "Eunotia subherkiniensis", species_update := "Eunotia subherkiniensis"]
data[species == "Eunotia zazuminensis", species_update := "Eunotia zasuminensis"]
data[species == "Fragilaria arcus", species_update := "Hannaea arcus"]
data[species == "Fragilaria capucina", species_update := "Fragilaria capucina complex"]
data[species == "Fragilaria capucina var.vaucheriae", species_update := "Fragilaria capucina complex"]
data[species == "Fragilaria famelica", species_update := "Synedra famelica"]
data[species == "Fragilaria leptostauron", species_update := "Staurosira leptostauron"]
data[species == "Fragilaria nevadensis", species_update := "Fragilaria nevadensis"]
data[species == "Fragilaria parva", species_update := "Fragilaria parva"]
data[species == "Fragilaria pulchella var.constricta", species_update := "Fragilaria pulchella var.constricta"]
data[species == "Fragilaria tenera var.nanana", species_update := "Fragilaria tenera var.nanana"]
data[species == "Fragilaria vaucheriae var.elliptica", species_update := "Fragilaria vaucheriae var.elliptica"]
data[species == "Genkalia digitulus", species_update := "Genkalia digitulus"]
data[species == "Gomphoneis minuta", species_update := "Gomphonema kociolekii"]
data[species == "Gomphonema bohemicum", species_update := "Gomphonema bohemicum"]
data[species == "Gomphonema elegans", species_update := "Gomphoneis elegans"]
data[species == "Gomphonema elegantissimum", species_update := "Gomphonema elegantissimum"]
data[species == "Gomphonema goronatum", species_update := "Gomphonema goronatum"]
data[species == "Gomphonema minutum f.curtum", species_update := "Gomphonema minutum var.curtum"]
data[species == "Gomphonema minutum f.syriacum", species_update := "Gomphonema minutum var.syriacum"]
data[species == "Gomphonema olivaceum var.salina", species_update := "Gomphonema olivaceum/olivaceoides"]
data[species == "Gomphonema saprophilum", species_update := "Gomphonema saprophilum"]
data[species == "Gomphonema tenoccultum", species_update := "Gomphonema tenoccultum"]
data[species == "Gomphonemopsis exigua var.platypus", species_update := "Gomphonemopsis exigua var.platypus"]
data[species == "Humidophila contenta", species_update := "Humidophila contenta"]
data[species == "Humidophila gallica", species_update := "Humidophila gallica"]
data[species == "Humidophila perpusilla", species_update := "Humidophila perpusilla"]
data[species == "Humidophila schmasmannii", species_update := "Humidophila schmasmannii"]
data[species == "Kolbesia gessneri", species_update := "Kolbesia gessneri"]
data[species == "Krasskella hyalina", species_update := "Krasskella hyalina"]
data[species == "Mayamaea atomus", species_update := "Mayamaea atomus"]
data[species == "Mayamaea atomus var.alcimonica", species_update := "Mayamaea atomus var.alcimonica"]
data[species == "Mayamaea fossalis", species_update := "Mayamaea fossalis"]
data[species == "Mayamaea fossalis var.obsidialis", species_update := "Mayamaea fossalis var.obsidialis"]
data[species == "Mayamaea ingenua", species_update := "Mayamaea ingenua"]
data[species == "Mayamaea lacunolaciniata", species_update := "Mayamaea lacunolaciniata"]
data[species == "Mayamaea permitis", species_update := "Mayamaea permitis"]
data[species == "Meridion circulare", species_update := "Meridion circulare"]
data[species == "Navicula atomus", species_update := "Mayamaea atomus"]
data[species == "Navicula cryptocephala f.terrestris", species_update := "Navicula cryptocephala var.terrestris"]
data[species == "Naviculadicta lange-bertalot", species_update := "Naviculadicta langebertalotii"]
data[species == "Navicymbula pusilla", species_update := "Navicymbula pusilla"]
data[species == "Nitzschia amabilis", species_update := "Nitzschia amabilis"]
data[species == "Nitzschia capitellata var.tenuirostris", species_update := "Nitzschia capitellata var.tenuirostris"]
data[species == "Nitzschia filiformis", species_update := "Nitzschia filiformis"]
data[species == "Nitzschia frustulum", species_update := "Nitzschia frustulum"]
data[species == "Nitzschia frustulum var.inconspicua", species_update := "Nitzschia inconspicua"]
data[species == "Nitzschia liebetruthii", species_update := "Nitzschia liebetruthii"]
data[species == "Nitzschia linearis", species_update := "Nitzschia linearis"]
data[species == "Nitzschia subtilissima", species_update := "Nitzschia subtilis"]
data[species == "Nupela lapidosa", species_update := "Nupela lapidosa"]
data[species == "Odontidium hyemale", species_update := "Odontidium hyemale"]
data[species == "Odontidium mesodon", species_update := "Odontidium mesodon"]
data[species == "Pinnularia biceps", species_update := "Pinnularia biceps"]
data[species == "Pinnularia borealis", species_update := "Pinnularia borealis"]
data[species == "Pinnularia divergens", species_update := "Pinnularia divergens"]
data[species == "Pinnularia divergentissima", species_update := "Pinnularia divergentissima"]
data[species == "Pinnularia lundii", species_update := "Pinnularia lundii"]
data[species == "Pinnularia mesolepta", species_update := "Pinnularia mesolepta"]
data[species == "Pinnularia microstauron", species_update := "Pinnularia microstauron"]
data[species == "Pinnularia nodosa", species_update := "Pinnularia nodosa"]
data[species == "Pinnularia polyonca", species_update := "Pinnularia polyonca"]
data[species == "Pinnularia subcapitata", species_update := "Pinnularia subcapitata"]
data[species == "Pinnularia subgibba", species_update := "Pinnularia subgibba"]
data[species == "Pinnularia viridiformis", species_update := "Pinnularia viridiformis"]
data[species == "Pinnularia viridis", species_update := "Pinnularia viridis"]
data[species == "Planothidium rostratoholarcticum", species_update := "Planothidium rostratoholarcticum"]
data[species == "Platessa oblongella", species_update := "Platessa oblongella"]
data[species == "Psammothidium rechtense", species_update := "Psammothidium rechtense"]
data[species == "Psammothidium subsalsum", species_update := "Psammothidium subsalsum"]
data[species == "Pseudofallacia occulta", species_update := "Pseudofallacia occulta"]
data[species == "Reimeria capitata", species_update := "Reimeria capitata"]
data[species == "Rossithidium linearis", species_update := "Rossithidium linearis"]
data[species == "Sellaphora ventraloides", species_update := "Sellaphora ventraloides"]
data[species == "Skeletonema potamos", species_update := "Skeletonema potamos"]
data[species == "Stauroneis kriegerii", species_update := "Stauroneis kriegerii"]
data[species == "Stauroneis phonicenteron", species_update := "Stauroneis phonicenteron"]
data[species == "Stephanodiscus neoastraea", species_update := "Stephanodiscus neoastraea"]
data[species == "Stephanodiscus vestibulis", species_update := "Stephanodiscus vestibulis"]
data[species == "Surirella angusta f.punctata", species_update := "Surirella angusta Complex"]
data[species == "Surirella brebissonii", species_update := "Surirella brebissonii"]
data[species == "Surirella lacrimula", species_update := "Surirella lacrimula"]
data[species == "Tetracyclus rupestris", species_update := "Tetracyclus rupestris"] 
data[species == "Karayevia clevei", species_update := "Karayevia clevei"] 
data[species == "Rhopalodia parallela", species_update := "Rhopalodia parallela"] 
